バリデーションを追加
yanbaru-expert/team_project_42 pull request #33
Opened 2021-02-08 02:22 UTC by Shuto-Toyama

## close #8 

## 実装内容

### タスク4 で作成した2種類のモデルに，各カラムに空データが入らないようにするバリデーションを追加
 - `app/models/movie.rb`に`validates :genre, :title, :content, presence: true`を追加
 - `app/models/text.rb`に  `validates :genre, :title, :content, presence: true`を追加
 - `db/migrate/20210206203632_create_texts.rb`の各カラムに`null: false`を追加
 - `db/migrate/20210206203754_create_movies.rb`の各カラムに`null: false`を追加
 
## 参考資料

  - [migrationファイル内のnull: falseとは](https://qiita.com/ryuuuuuuuuuu/items/2841cddf8b541c336ebd)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-08 07:08 UTC, ajk0421 requested changes

2021-02-08 07:08 UTC, ajk0421 commented on app/models/movie.rb
> +  validates :genre, :title, :url, presence: true
この書き方はあまりおすすめしません！
対象のカラムが増えるとどんどん横に長くなるので可読性が悪くなります！
まとめて書きたい場合は `with_opion` を使うか、一行つづ書くようにしましょう！

2021-02-08 07:08 UTC, ajk0421 commented on app/models/text.rb
> +  validates :genre, :title, :content, presence: true
こちらも同じです！

2021-02-08 07:08 UTC, ajk0421 commented on db/migrate/20210206203632_create_texts.rb
> +      t.text :content, null: false
一度作成したmigrationファイルの編集はしてはいけません！
新しくオプションを追加する場合は、それようのmigrationファイルを作成しましょう！

2021-02-08 13:39 UTC, Shuto-Toyama commented on app/models/text.rb
>  end
> まとめて書きたい場合は with_opion を使うか、一行つづ書くようにしましょう！
- １行づつの記述に変更致しました。

2021-02-08 13:43 UTC, Shuto-Toyama commented on app/models/text.rb
> +  validates :genre, :title, :content, presence: true
承知致しました！

2021-02-08 13:46 UTC, Shuto-Toyama commented on app/models/movie.rb
> +  validates :genre, :title, :url, presence: true
確認致しました。
一行つづ記載します！

2021-02-08 13:47 UTC, Shuto-Toyama commented on db/migrate/20210206203632_create_texts.rb
> +      t.text :content, null: false
確認致しました。
編集を削除してそれぞれ追加用のmigrateファイルを作成致します！

2021-02-09 05:20 UTC, ajk0421 approved these changes
OKです！
マージしてください！

2021-02-09 05:48 UTC, merged