ログイン機能の実装
yanbaru-expert/team_project_42 pull request #36
Opened 2021-02-10 14:26 UTC by yamada1013

## close #5 

## 実装内容

・devise を利用して，ユーザーのログイン機能を実装
・新規登録・ログイン・ログアウトのリンクを，全てのページの一番上に追加
・db/seeds.rb にテスト用ユーザーを作成できるように設定
・全てのページを「ログイン必須」に変更

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-12 06:10 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +    <% end %>
```suggestion
    <% if user_signed_in? %>
      <!-- ログイン時 -->
      <%= link_to "アカウント編集", edit_user_registration_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
    <% else %>
      <!-- 非ログイン時 -->
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "アカウント登録", new_user_registration_path %>
    <% end %>
```

2021-02-12 06:11 UTC, ajk0421 requested changes
一点だけ修正お願いします！

2021-02-12 08:37 UTC, yamada1013 commented on app/views/layouts/application.html.erb
> +    <% end %>
コメントありがとうございます。
修正致しました。

2021-02-12 08:57 UTC, yamada1013 commented on app/views/layouts/application.html.erb
> +    <% end %>
何度も申し訳ございません。
修正しました。

2021-02-13 06:50 UTC, ajk0421 approved these changes
コンフリクトしてるので解消してください！

2021-02-13 15:49 UTC, yamada1013 commented
> コンフリクトしてるので解消してください！

2021-02-13 15:51 UTC, yamada1013 commented
> > コンフリクトしてるので解消してください！

2021-02-13 23:05 UTC, yamada1013 commented on app/views/layouts/application.html.erb
> +    <% end %>
コメントありがとうございます。

ローカルでコンフリクト後に
git add .
git commit - をしている最中にmacのターミナルがシャットダウンしましたのでgit commit できなくなりましたので
ファイル(app/views/layouts/application.html.erb)を
1文字ずらして変更して 
git add .
git commit -m "変更"
再度ファイル(app/views/layouts/application.html.erb)を
1文字戻して
git add .
git commit -m "コンフリクト"
git push origin HEADしました。

mergeしてよろしいでしょうか?

2021-02-16 12:51 UTC, Hiroto-Iizuka commented
ヤマダさん

お疲れさまです！
報告です！
私のissue#14 でgem 'devise'をインストールしてしまっているのですが、
ヤマダさんの行っているissueで最初につけておく必要がありそうです。

こちらがアンインストールしたので、気にせず進めてしまっていいと思います！

2021-02-17 13:48 UTC, merged

2021-02-17 13:56 UTC, yamada1013 commented
Iizukaさん

お疲れさまです。
かしこまりした！！