管理者画面の実装(adminuser, user, text, movieを追加できるように設定)
yanbaru-expert/team_project_42 pull request #37
Opened 2021-02-14 14:02 UTC by Hiroto-Iizuka

## issue 14

close #14

## 実装内容

- Active Adminで管理者画面を実装
  - `db/seeds.rb`を何度実行してもエラーが起きないように修正
  - 動画、テキスト教材を管理者画面から登録できるように設定
  - 管理者画面以外のスタイルに影響が出ないよう`css`と`js`を`vendor`ディレクトリに移動

## 参考資料

- やんばるCODEアプリ
  - [管理者画面](https://www.yanbaru-code.com/texts/220)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考

- 日本語化については#issue6で実装予定なので未実装

2021-02-16 03:49 UTC, ajk0421 commented on Gemfile
> +gem 'devise'
```
gem 'devise'
```
他のタスクで導入予定なので相談が必要ですね！

2021-02-16 03:50 UTC, ajk0421 commented on db/seeds.rb
> +AdminUser.find_or_create_by!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
こちら
```
rails db:seed
```
は通りましたか？

2021-02-16 03:51 UTC, ajk0421 requested changes
全体的に他の方のPRの実装との依存関係があると思うので整理して実装しましょう！

2021-02-16 12:24 UTC, Hiroto-Iizuka commented on Gemfile
> +gem 'devise'
共通事項は影響が広範囲なのでチームメンバーとの相談が必要なんですね！
承知しました！

2021-02-16 12:38 UTC, Hiroto-Iizuka commented on db/seeds.rb
> +AdminUser.find_or_create_by!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
よく見たら途中で止まってました。。
修正致します！

2021-02-21 13:33 UTC, ajk0421 requested changes
どのように管理画面に入れば良いでしょうか？
また、 `ユーザー，動画，テキスト教材を管理者画面から追加できるように設定` こちら確認されましたか？？？

2021-02-24 21:20 UTC, closed without merging