日本語化
yanbaru-expert/team_project_42 pull request #39
Opened 2021-02-18 09:10 UTC by yamada1013

## issue 番号6
close #6 

## 実装内容

原則，マークダウン記法のリストで記載すること

(例)

- 日本語化
  - rails-i18n, devise-i18nのgemを追加
  - 日本語の設定とタイムゾーンの変更 

- やんばるCODEアプリ
  - [ログイン機能](https://www.yanbaru-code.com/texts/219)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-02-19 08:05 UTC, ajk0421 requested changes
こちら、日本語化されているかどうかどのように確認しましたか？？

2021-02-19 08:05 UTC, ajk0421 commented on Gemfile
> +# 多言語対応(Rails 6の場合)
```
# 多言語対応(Rails 6の場合)
```
こちらのコメントはどういった理由で残されましたか？

2021-02-20 07:25 UTC, yamada1013 reviewed
コメントありがとうございます。
教材の中の[ログインページの日本語化]で
記載されてましたので、そのまま記載しました。
https://www.yanbaru-code.com/texts/219

2021-02-20 07:25 UTC, yamada1013 commented on Gemfile
> +# 多言語対応(Rails 6の場合)
コメントありがとうございます。
教材の中の[ログインページの日本語化]で
記載されてましたので、そのまま記載しました。
https://www.yanbaru-code.com/texts/219

2021-02-20 15:07 UTC, ajk0421 commented
ちょっとだけ厳しいですが、これだと、ただ教材をコピペしてきて、動作確認もしていないけどレビューお願いします！
という状態です。

今後レビュー依頼する時は必ず以下に注意してください！

- ただ教材をコピペしない
- 必ず動作確認をしてからレビュー依頼を出してください


### 残タスク
以下のように進めてみてください！

1. 使用していない余計なコメントを削除
2. 以下のファイルを `locale` 配下に `devise.views.ja.yml` として設置
- https://github.com/tigrish/devise-i18n/blob/master/rails/locales/ja.yml

3. 以下のファイルを `locale` 配下に `ja.yml` として設置
- https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ja.yml

不明点あれば聞いてください！

2021-02-22 07:14 UTC, yamada1013 commented
申し訳ございません訂正致しました。
質問させて下さい。
動作確認をしてからレビュー依頼は訂正後にrailsのサーバーを立ち上げて
実際に実装したように動くかを確認する認識でよろしかったでしょうか?

[2.以下のファイルを locale 配下に devise.views.ja.yml として設置]
↑
こちらの動作確認は新規登録、アカウント削除などで確認しました。

[3.以下のファイルを locale 配下に ja.yml として設置]
↑
こちらの動作確認はどのようにすればよろしいでしょうか?

ご教示のほどお願い申し上げます。

2021-02-22 08:16 UTC, ajk0421 commented
> [3.以下のファイルを locale 配下に ja.yml として設置]
> ↑
> こちらの動作確認はどのようにすればよろしいでしょうか?
> 
> ご教示のほどお願い申し上げます。

今回ですと、以下のようにチェックする方法が簡単だと思います！

https://qiita.com/mishiwata1015/items/2ca75661ea618a6ec5ae

2021-02-22 09:21 UTC, yamada1013 commented
>今回ですと、以下のようにチェックする方法が簡単だと思います！
>https://qiita.com/mishiwata1015/items/2ca75661ea618a6ec5ae

動作確認できました。

2021-02-22 15:55 UTC, ajk0421 approved these changes
OKです！
マージしてください！！

2021-02-23 06:57 UTC, merged