Bootstrapの導入
yanbaru-expert/team_project_42 pull request #40
Opened 2021-02-19 07:52 UTC by yamada1013

## issue 番号 7

close #7

## 実装内容

- Bootstrap を導入
  - トップページに動作確認用のボタンを1個配置
  - css は Sprocketsを使用  

## 参考資料

- やんばるCODEアプリ
  - [Bootstrap の導入](https://www.yanbaru-code.com/texts/216)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-02-19 08:28 UTC, ajk0421 requested changes

2021-02-19 08:28 UTC, ajk0421 commented on app/assets/stylesheets/application.scss
> +@import "bootstrap/scss/bootstrap";
これは上部に書いた方が良いです！

2021-02-19 08:28 UTC, ajk0421 commented on app/views/texts/index.html.erb
> +<button type="button" class="btn btn-primary">Primary</button>
こちらは今回のアプリで使用する予定はありますか？

2021-02-19 08:28 UTC, ajk0421 commented on config/webpack/environment.js
> +// ***** 以下を追加 *****
こちらのコメント達はどういった理由で残されましたか？？

2021-02-20 07:55 UTC, yamada1013 commented on app/assets/stylesheets/application.scss
> +@import "bootstrap/scss/bootstrap";
承知しました。

2021-02-20 07:55 UTC, yamada1013 commented on config/webpack/environment.js
> +// ***** 以下を追加 *****
コメントありがとうございます。
こちらも[多言語対応(Rails 6の場合)]の時と同じく教材に書いてある通りに記載してしまいました。
消した方がよろしいでしょうか?

2021-02-20 07:55 UTC, yamada1013 commented on app/views/texts/index.html.erb
> +<button type="button" class="btn btn-primary">Primary</button>
[issues.md]の[8. Bootstrapの導入実装内容]に
[トップページに動作確認用のボタンを1個配置すること]と記載されておりましたので書いたんですが
間違っておりますでしょうか?
https://github.com/yanbaru-expert/team_project_42/blob/develop/issues.md

2021-02-20 15:10 UTC, ajk0421 commented
こちらも同様ですが、ただ教材をコピペするのではなく、どういう目標物を作るか意識して実装しましょう！

2021-02-20 15:13 UTC, ajk0421 commented on app/views/texts/index.html.erb
> +<button type="button" class="btn btn-primary">Primary</button>
あー、なるほど！
では、動作確認出来たので、これは削除しちゃいましょうか！

2021-02-20 15:17 UTC, ajk0421 requested changes

2021-02-20 15:17 UTC, ajk0421 commented on config/webpack/environment.js
> +// ***** 以下を追加 *****
必要ないコメントは削除しましょう！

2021-02-22 06:53 UTC, yamada1013 commented on app/views/texts/index.html.erb
> +<button type="button" class="btn btn-primary">Primary</button>
かしこまりました。

2021-02-22 06:53 UTC, yamada1013 commented on config/webpack/environment.js
> +// ***** 以下を追加 *****
承知しました。

2021-02-22 08:52 UTC, ajk0421 approved these changes
OKです！マージしてください！

2021-02-22 09:04 UTC, merged