ナビバーの実装
yanbaru-expert/team_project_42 pull request #49
Opened 2021-02-26 08:45 UTC by yamada1013

## issue 番号 9

close #9

## 実装内容

- ナビバーの実装
  - 「タスク6」で作成された「新規登録・ログアウトなどのリンク」は削除
  - 「新規登録」のリンクも追加
  - ナビバーのリンクは「新規登録」「ログイン」「ログアウト」と「テキスト教材」ページのみ有効にし他は href 属性を # 
  - ナビバーは fixed-top クラスを利用して上に固定されるようにすること

## 参考資料

マークダウン記法のリンクを用いて記載すること

(例)

- 公式
  - [Bootstrap（Navbar）](https://getbootstrap.jp/docs/4.5/components/navbar/)

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-26 10:28 UTC, ajk0421 requested changes
https://github.com/yanbaru-expert/team_project_42/pull/49#issue-580700085

ここに書いてある内容は全て確認しましたか？

2021-02-26 10:28 UTC, ajk0421 commented on app/views/layouts/_header.html.erb
> +          <% end %>
```suggestion
          <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              マイページ
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">進歩管理</a>
              <a class="dropdown-item" <%= link_to "アカウント編集", edit_user_registration_path %></a>
              <a class="dropdown-item" <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %></a>
            </div>
          <% else %>
            <li class="nav-item">
              <a class="nav-link"<%= link_to "ログイン", new_user_session_path %>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link"<%= link_to "新規登録", new_user_registration_path %>
              </a>
            </li>
          <% end %>
```

rubyを書くときと同じように、インデント意識しましょう！

2021-02-27 00:36 UTC, yamada1013 commented on app/views/layouts/_header.html.erb
> +          <% end %>
コメントありがとうございます。
申し訳ございませんが見落としてました。
再度インデントしましたので確認お願いします。

2021-02-27 00:46 UTC, ajk0421 requested changes
実装内容に
 `ナビバーのリンクは「新規登録」「ログイン」「ログアウト」と「テキスト教材」ページのみ有効にし他は href 属性を #`
このように記載されていますが、全て確認されましたか？？

2021-02-27 03:33 UTC, yamada1013 commented
コメントありがとうございます。
>実装内容に
>ナビバーのリンクは「新規登録」「ログイン」「ログアウト」と「テキスト教材」ページのみ有効にし他は href 属性を #
>このように記載されていますが、全て確認されましたか？？

申し訳ございません。
こちらもアカウント編集にリンクをつけていました。
質問させていただきたいのでですが
>「テキスト教材」ページのみ有効
とはテキスト教材と付くのが複数ありますが下記にリンクを入れるという事でしょうか?
下記のリンクはどこで確認すればよろしいでしょうか?
ご教示いただけますと幸いです

Ruby/Railsテキスト教材
AWSテキスト教材
PHPテキスト教材

2021-02-27 16:50 UTC, ajk0421 reviewed
https://github.com/yanbaru-expert/team_project_42/blob/develop/config/routes.rb#L4

こちらに関しては、今回対応しない感じでしょうか？？

2021-02-28 07:15 UTC, yamada1013 commented
申し訳ございません。
知識不足でdevise_for :usersの対応する、しないの理解できていないのですが
下記に記載してあるようするということでしょうか?

https://qiita.com/hakatatech/items/f991d54ff527edb844d9

https://qiita.com/Yama-to/items/54ab4ce08e126ef7dade

ご教示いただけますと幸いです。

2021-03-01 08:25 UTC, ajk0421 commented
> 申し訳ございません。
> 知識不足でdevise_for :usersの対応する、しないの理解できていないのですが
> 下記に記載してあるようするということでしょうか?
> 
> https://qiita.com/hakatatech/items/f991d54ff527edb844d9
> 
> https://qiita.com/Yama-to/items/54ab4ce08e126ef7dade
> 
> ご教示いただけますと幸いです。

大変申し訳ないです！
指定の行がずれていました・・

https://github.com/yanbaru-expert/team_project_42/blob/develop/config/routes.rb#L6

こちらが正しいです！

2021-03-01 11:24 UTC, yamada1013 commented
コメントありがとうございます。
Ruby/Railsテキスト教材のリンクを加えました。

2021-03-01 12:23 UTC, ajk0421 approved these changes
OKです！
マージしてください！

2021-03-01 14:31 UTC, merged