読破済み機能の実装
yanbaru-expert/team_project_42 pull request #53
Opened 2021-03-04 06:49 UTC by Shuto-Toyama

## 読破済み機能の実装
close #42 

## 実装内容

＊Railsテキスト教材一覧ページの実装 #15完了後に実施

  - read/migrate/model/controllerファイルを作成
  - Railsメイン/詳細ページへの読破済ボタン反映
  - js.erbを用いて非同期でのボタン変更の確認
  - メインページカード内のボタンレイアウトに加え、ホバー時の下線除去/テキストの色を設定

## 参考資料

- モデルの関連付け その2（多対多）
  - [やんばるCODEアプリ](https://www.yanbaru-code.com/texts/297)

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

【備考】

-  その他テキストページへのボタン機能反映/動画教材の「視聴済み機能」は別タスクで行います。

2021-03-04 13:45 UTC, ajk0421 requested changes
お疲れ様です！
コメントしましたー！！

2021-03-04 13:45 UTC, ajk0421 commented on app/assets/stylesheets/application.scss
> +a:hover {
`aタグ` 対して直接スタイルを当てるのはよくありません！
他の箇所で `aタグ` を使用した場合、同じようにスタイルが当たってしまうからですね！
一度、classを付与して、その上でスタイルを当てましょう！

2021-03-04 13:45 UTC, ajk0421 commented on app/controllers/reads_controller.rb
> +    current_user.reads.find_by(text_id: @text.id).destroy!
- データを取得
- データを削除
これは分けて書きましょう！

2021-03-04 13:45 UTC, ajk0421 commented on app/views/texts/index.html.erb
> +                <% end %>
ここですが、パーシャルは1つにして、その中で条件分岐して表示する方がスマートかもですね！
render先を１箇所にして、下記のように書いたら上手くいかないですかね？？
```
<% if @read_text_ids.include?(text.id) %>
  <%= link_to '読破済みを解除', text_reads_path(text), class: 'btn btn-primary btn-block', method: :delete, remote: true %>
<% else %>
  <%= link_to '読破済みにする', text_reads_path(text), class: 'btn btn-secondary btn-block', method: :post, remote: true %>
<% end %>

2021-03-04 19:20 UTC, Shuto-Toyama commented on app/assets/stylesheets/application.scss
> +a:hover {
コメントありがとうございます！
class付与の修正致します。

2021-03-04 19:21 UTC, Shuto-Toyama commented on app/controllers/reads_controller.rb
> +    current_user.reads.find_by(text_id: @text.id).destroy!
コメントありがとうございます！
こちらは
`before_action :set_text`
を使わずにcreate/destroyアクションそれぞれに
`@text = Text.find(params[:text_id])`
を記載すべきということでしょうか？

2021-03-05 02:38 UTC, Shuto-Toyama commented on app/views/texts/index.html.erb
> +                <% end %>
コメントありがとうございます！
> ここですが、パーシャルは1つにして、その中で条件分岐して表示する方がスマートかもですね！
> render先を１箇所にして、下記のように書いたら上手くいかないですかね？？

```
<% if @read_text_ids.include?(text.id) %> 
  <%= link_to '読破済みを解除', text_reads_path(text), class: 'btn btn-primary btn-block', method: :delete, remote: true %> 
<% else %> 
  <%= link_to '読破済みにする', text_reads_path(text), class: 'btn btn-secondary btn-block', method: :post, remote: true %> 
<% end %>
```

上記挑戦させていただきました。
-  パーシャルを`_read.html.erb`のみとして、上記の通り記述し`_unread.html.erb`を削除
-  `texts/index.html.erb`を以下の通り編集

```
 <div id="text-<%= text.id %>">
    <%= render "read", text: text %>
 </div>
```
へ変更したところ、非同期処理が効かなくなってしまいました。
試したこと` views/reads/destroy.js.erb`のパスをunread→readに変更
` document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'`
お手数ですがアドバイス頂けますでしょうか？

2021-03-06 06:23 UTC, ajk0421 commented on app/views/texts/_read.html.erb
> +<% if @read_text_ids.include?(text.id) %>
`read_by?メソッド` で判定しましょう！

2021-03-06 06:24 UTC, ajk0421 requested changes

2021-03-06 06:24 UTC, ajk0421 commented on app/views/texts/_read.html.erb
> +<% if @read_text_ids.include?(text.id) %>
`read_by?メソッド` で判定しましょう！

2021-03-06 06:24 UTC, ajk0421 commented on app/views/reads/create.js.erb
> +document.getElementById('text-<%= text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'
app/views/reads/destroy.js.erb

と見比べてみましょう！

2021-03-07 05:28 UTC, Shuto-Toyama commented on app/views/texts/_read.html.erb
> +<% if @read_text_ids.include?(text.id) %>
read_by?メソッドに修正致しました。

2021-03-07 05:29 UTC, Shuto-Toyama commented on app/views/reads/create.js.erb
> +document.getElementById('text-<%= text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'
修正致しました！

2021-03-08 03:11 UTC, ajk0421 requested changes

2021-03-08 03:11 UTC, ajk0421 commented on app/controllers/reads_controller.rb
> +    @text = Text.find(params[:text_id])
```
@text = Text.find(params[:text_id])

```
ここは、before_actionでまとめましょう！

2021-03-08 03:11 UTC, ajk0421 commented on app/controllers/reads_controller.rb
> +    current_user.reads.find_by(text_id: @text.id).destroy!
```
current_user.reads.find_by(text_id: @text.id).destroy!

```
ここは
- データの取得
- データの削除
で行を分けましょう！
1行にあまり多くの処理を持たせないようにした方が良いです！

2021-03-08 03:11 UTC, ajk0421 commented on app/controllers/reads_controller.rb
> +    current_user.reads.find_by(text_id: @text.id).destroy!
```
current_user.reads.find_by(text_id: @text.id).destroy!

```
ここは
- データの取得
- データの削除
で行を分けましょう！
1行にあまり多くの処理を持たせないようにした方が良いです！

2021-03-08 03:37 UTC, Shuto-Toyama commented on app/controllers/reads_controller.rb
> +    @text = Text.find(params[:text_id])
before_actionにまとめました！

2021-03-08 03:41 UTC, Shuto-Toyama commented on app/controllers/reads_controller.rb
> +    current_user.reads.find_by(text_id: @text.id).destroy!
前回のレビューを`「[before_action]を使用すべきではない」`という風に理解してしまってました。

- データの取得　`@read = current_user.reads.find_by(text_id: @text.id)`
- データの削除　`@read.destroy!`

分けて記述しました。

2021-03-08 05:44 UTC, ajk0421 requested changes

2021-03-08 05:44 UTC, ajk0421 commented on app/controllers/reads_controller.rb
> +    @read.destroy!
`@read` ここはインスタンス変数にしてる理由はなにかありますか？？

2021-03-08 05:52 UTC, Shuto-Toyama commented on app/controllers/reads_controller.rb
> +    @read.destroy!
申し訳ありません、無自覚に@readとしておりました。
@read = read　へ変更致しました。

2021-03-08 06:02 UTC, ajk0421 approved these changes
OKです！
マージしてください！

2021-03-08 06:03 UTC, merged