php_text関連のファイルを削除し、link_toのパラメータから各ジャンルの一覧画面に遷移できるように実装 #55
yanbaru-expert/team_project_42 pull request #59
Opened 2021-03-08 14:29 UTC by satou54

## issue 番号 #55 

close #55 

## 実装内容

- php_texts関連のファイルを削除
  - php_texts_controller.rbを削除
  - views/php_texts/index.html.erbを削除
  - views/php_texts/show.html.erbを削除
  - routes.rbからphp_texts_controllerのrouteを削除

- link_toのパラメータから各ジャンルの一覧画面に遷移できるように実装
  - texts_controller.rbのindexを修正
    - 送られてきたパラメータによって変数`genre`を変更し、Textモデルのgenreカラムからデータを検索するように修正
    - 送られてきたパラメータによって一覧画面のタイトルに使用する変数`@title`を変更するように修正
  - view/texts/index.html.erbを修正
    - 一覧画面のタイトルを`@title`によって変更するように修正

- _header.html.erbからのリンクを修正
  - 全てのリンクを`<a>`タグから`link_to`に変更
  - AWSテキスト教材、PHPテキスト教材へのリンクにパラメータを指定

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考（必要があれば）

2021-03-08 15:50 UTC, ajk0421 requested changes
色々コメントしてますが、１つづ修正してみてください！

2021-03-08 15:50 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +    @texts = Text.where(genre: genre)
```
case genre
    when "php"
      genre = "Php"
      @title = "PHP"
    when "aws"
      genre = @title = "AWS"
    when nil
      genre = ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
      @title = "Ruby/Rails"
    end
```
こういったロジックをコントローラーのアクション内に直書きするのやめましょう！

- コントローラー内のprivateメソッド
- クラスメソッド

に寄せるのが良いと思います。

今回だと、 `privateメソッド` が良いかもですね！

イメージ的にはこんな感じで呼び出せると良いかもです！

```
class TextsController < ApplicationController
  before_action :set_texts, only: :index

  def index
  end

private
  def set_texts
    # ロジック
  end

end

2021-03-08 15:50 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +      genre = "Php"
```
genre = params[:genre]



genre = "Php"

```
こういった再代入はよくないので、これをせず実装してみてください！
※他の該当箇所も確認お願いします。

2021-03-09 11:18 UTC, satou54 commented
ご確認ありがとうございます！
下記の対応を行いましたので、再度ご確認お願いいたします。
動作確認は行っております。

- indexアクション内のロジックをpriveteメソッドに切り分け
- 変数`genre`に再代入せず、新しく`search_genre`という変数を定義し、case文の結果を代入

2021-03-09 12:21 UTC, ajk0421 requested changes

2021-03-09 12:21 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +    @search_genre = case genre
```
@search_genre
```
インスタンス変数は基本 `viewで使う時だけ` 定義しましょう！

今回は、set_textsメソッドの中で

```
@texts = Text.where(genre: @search_genre)
```

これをやるイメージです！

2021-03-09 15:55 UTC, satou54 commented
お疲れ様です！
`@search_genre`を修正し、set_texts内でTextモデルから検索するように修正いたしました。

```
def set_texts
    genre = params[:genre]

    search_genre = case genre
      when "php"
        @title = "PHP"
        "Php"
      when "aws"
        @title = "AWS"
        "AWS"
      when nil
        @title = "Ruby/Rails"
        ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
      end

    @texts = Text.where(genre: search_genre)
end
```

2021-03-11 03:42 UTC, ajk0421 approved these changes
OKです！

2021-03-11 12:28 UTC, merged