検索機能を実装 #38
yanbaru-expert/team_project_42 pull request #61
Opened 2021-03-11 22:01 UTC by satou54

## #38 

close #38

## 実装内容

- 検索機能を実装
  - Gemfileを修正
    - `ransack`を追加
    -  `font-awesome-rails`を追加
      - assets/stylesheets/application.scssに`@import "font-awesome";`を追加
  - texts/index.html.erbに検索機能を追加
    - inputで`title`を入力できる
    - hidden_fieldで`@genre`を入力することで現在表示しているジャンルの記事から`title`で検索できるように実装
    - submitにfontawesomeを適用
  - texts_controller.rbを修正
    - set_qメソッドを作成し、ストロングパラメータを設定
    - set_qメソッドをindexアクションのbefore_actionに設定
    - `genre`を`@genre`に修正
    - キーワード検索か一覧表示かを判定する変数`search_flg`を作成
    - `params[:q]`に値が存在する場合は`search_flg`を`true`に変更し、`@genre`に`params[:q]["genre"]`を代入
    - case文に`@genre`がblankの場合を追加
    - `search_flg`が`true`の場合、`@genre`で記事を絞った後に`params[:q]`で`title`をあいまい検索
    - あいまい検索後に`search_flg`を`false`に変更
    - `search_flg`が`false`の場合、`genre`カラムを`search_genre`で検索

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考（必要があれば）

2021-03-12 02:35 UTC, ajk0421 requested changes
今回、コントローラーの記載を少し見直したかったのですが、さとうさんは色々考えながらコードを書いているのが伝わってくるの、一旦サンプルコードを書きました！

- ここが分かりにくい
- ここはこう言うふうに書くのはどうですか？

という意見があればコメント逆にください！
踏まえて、修正して頂けると！

```
class TextsController < ApplicationController

  def index
    @q = set_texts.ransack(params[:q])
    @texts = @q.result
  end

  def show
    @text = Text.find(params[:id])
  end

  private

  def set_texts
    @genre = params[:genre]

    search_genre = case @genre
      when "php"
        @title = "PHP"
        "Php"
      when "aws"
        @title = "AWS"
        "AWS"
      else
        @title = "Ruby/Rails"
        ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
      end

    texts = Text.where(genre: search_genre)

    texts
  end
end
```

2021-03-13 01:19 UTC, satou54 commented
お疲れ様です！
サンプルコードありがとうございます！

基本的にあじーさんのサンプルコードのままですが、一点だけ修正したい箇所があります。
`@genre = params[:genre]`ではなく、`params[:q] ? @genre = params[:q]["genre"] : @genre = params[:genre]`に変更したいと考えています。

理由としては、キーワード検索する場合パラメータからgenreが消えてしまうため、`params[:genre]`で値を取得することができません。値を取得することができないとphpテキスト教材の画面にも関わらず、case文で""が条件に一致するためタイトルにRuby/Railsテキスト教材が表示されてしまいます。

そのため、viewの検索フォームでhidden_formを使って`@genre`の値を送信し、controllerで`@genre = params[:q]["genre"] `として受け取ることで、検索前の一覧画面のタイトルのまま検索結果を表示できるようにしています。

なお、ローカル環境において動作確認は行っております。

```
class TextsController < ApplicationController
  def index
    @q = set_texts.ransack(params[:q])
    @texts = @q.result
  end

  def show
    @text = Text.find(params[:id])
  end

  private

  def set_texts
    params[:q] ? @genre = params[:q]["genre"] : @genre = params[:genre]

    search_genre = case @genre
      when "php"
        @title = "PHP"
        "Php"
      when "aws"
        @title = "AWS"
        "AWS"
      when nil
        @title = "Ruby/Rails"
        ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
      when ""
        @title = "Ruby/Rails"
        ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
      end

    @texts = Text.where(genre: search_genre)
  end
end
```

2021-03-14 16:06 UTC, ajk0421 commented
> params[:q] ? @genre = params[:q]["genre"] : @genre = params[:genre]

理解しました！

ただ

```
params[:q] ? @genre = params[:q]["genre"] : @genre = params[:genre]
```
この三項演算子は少し見通しが悪いので、ノーマルのif文で書きましょう！

2021-03-14 16:57 UTC, satou54 commented
>params[:q] ? @genre = params[:q]["genre"] : @genre = params[:genre]
この三項演算子は少し見通しが悪いので、ノーマルのif文で書きましょう！

ご確認ありがとうございます！
三項演算子から通常のif文に修正しコミットしました！
再度ご確認よろしくお願いいたします。

2021-03-15 01:34 UTC, ajk0421 requested changes

2021-03-15 01:34 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +    if params[:q]
```suggestion
    if params[:q]["genre"].present?
```
こっちで書くべきですね！

今のままでは条件式と真の場合の処理の内容の整合性が取り切れていないです！

2021-03-15 01:34 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +        ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
```
when nil
  @title = "Ruby/Rails"
   ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
 when ""
   @title = "Ruby/Rails"
    ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
```

ここは `else` でまとめられないでしょうか？

2021-03-15 02:42 UTC, satou54 commented
ご確認ありがとうございます！
case分はelseでまとめて処理するように修正いたしました。

ただ、`if params[:q]["genre"].present?`に関しては修正していません。理由としては、`if params[:q]["genre"].present?`と記述すると`NoMethodError (undefined method `[]' for nil:NilClass):`とエラーが発生するためです。

リファレンス等の記述は見つけられませんでしたが、おそらく`params[:q]["genre]`を参照する場合はその前に`if params[:q]`で存在チェックを行ってからでないと使えないのだと思います。

そのため`if params[:q]["genre"].present?`を使用する場合、その前に`if params[:q]`を行ってから記述する必要があります。

ただ、`params[:q]["genre"]`はviewでhidden_fieldで記述しており、デベロッパーツール等で意図的にhidden_fieldを空にする場合を除いて`params[:q]`が存在する場合は`params[:q]["genre"]`も存在するという関係性になります。

そのため、修正せずに`if params[:q]`のままでも良いのではないかと考えていますがいかがでしょうか？

2021-03-15 03:22 UTC, ajk0421 commented
いいですね！！
こういうコミュニケーションが取れるのは素晴らしいです！

> ご確認ありがとうございます！
> case分はelseでまとめて処理するように修正いたしました。
👍 

> ただ、`if params[:q]["genre"].present?`に関しては修正していません。理由としては、`if params[:q]["genre"].present?`と記述すると`NoMethodError (undefined method `[]' for nil:NilClass):`とエラーが発生するためです。
> 
> リファレンス等の記述は見つけられませんでしたが、おそらく`params[:q]["genre]`を参照する場合はその前に`if params[:q]`で存在チェックを行ってからでないと使えないのだと思います。
> 
> そのため`if params[:q]["genre"].present?`を使用する場合、その前に`if params[:q]`を行ってから記述する必要があります。
> 
> ただ、`params[:q]["genre"]`はviewでhidden_fieldで記述しており、デベロッパーツール等で意図的にhidden_fieldを空にする場合を除いて`params[:q]`が存在する場合は`params[:q]["genre"]`も存在するという関係性になります。
> 
> そのため、修正せずに`if params[:q]`のままでも良いのではないかと考えていますがいかがでしょうか？


たしかにエラーが出ますね！理解です！
設計に関しても、承知しました！

2021-03-15 03:23 UTC, ajk0421 approved these changes
OKです！
マージしてください！

2021-03-15 03:35 UTC, merged