ページネーションの実装
yanbaru-expert/team_project_42 pull request #66
Opened 2021-03-15 11:10 UTC by yamada1013

## issue 番号 65

close #65 

## 実装内容

- ページネーション
  - gemfileにkaminariインストール
  - textsコントローラーとindexにページネーションを追加
  -  moviesコントローラーとindexにページネーションを追加
  - scssにページネーション中央に配置
 
## 参考資料

- 検索機能機能
  - [やんばるCODEアプリ](https://www.yanbaru-code.com/texts/221)

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-03-15 11:17 UTC, yamada1013 commented
コメント失礼します。
参考元サイトのページネーション部分が少し違う設計になっております。
できるだけ参考元サイトのレイアウトに近づけたいのですが
どのようにすればよろしいでしょうか?
ご教授お願い申し上げます。

参考元サイト [やんばるエキスパート]
https://www.yanbaru-code.com/texts


![スクリーンショット 2021-03-15 20 13 40](https://user-images.githubusercontent.com/63951478/111145260-66885c80-85cb-11eb-98d1-db5196d6cdd8.png)







![スクリーンショット 2021-03-15 20 13 49](https://user-images.githubusercontent.com/63951478/111145312-72741e80-85cb-11eb-89ed-3d4f32de993a.png)

2021-03-15 11:51 UTC, ajk0421 requested changes
各ページのPERが大きく変わらないのであれば `ApplicationRecord` でdefaultのPERを定義しておいて、変更がある場合、各modelでオーバーライドすると良いと思います！
(意味が分からない場合は聞いてください！)

2021-03-15 11:51 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +  PER_PAGE = 9
```
PER_PAGE = 9
```
定数はmodelに寄せましょうか！

2021-03-18 10:28 UTC, yamada1013 commented
>各ページのPERが大きく変わらないのであれば ApplicationRecord >>でdefaultのPERを定義しておいて、
>ApplicationRecord でdefaultのPERを定義しておいて、

⇩ApplicationRecordでdefault定義したんですが反映されなかったです。
   ApplicationRecordでどのようにPERを定義すればよろしいでしょうか?

```
class ApplicationRecord < ActiveRecord::Base
  paginates_per 3
  self.abstract_class = true
end
```

>>変更がある場合、各modelでオーバーライドすると良いと思います！
>>(意味が分からない場合は聞いてください！)

class ApplicationRecord < ActiveRecord::Baseで
defaultで定義した後
例えばtext.rbでどのようにオーバーライドすればよろしいでしょうか？

⇩class Text < ApplicationRecordでdefault定義したら反映されました。
```
class Text < ApplicationRecord
  has_many :users
  has_many :reads, dependent: :destroy
  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true
  
  paginates_per 3

  def read_by?(user)
    reads.find_by(user_id: user.id).present?
  end
end
```

ターミナルにrails g kaminari:views bootstrap4をすると
ページネーション部分が参考アプリのようなレイアウトになりましたが
rails g kaminari:views bootstrap4は実行してもよろしいでしょうか?

他の要らないファイルができるなどありますか?
bootstrapをbootstrap4に指定しましたが
現在package.jsonでは  "bootstrap": "^4.6.0",になっている場合でも
大丈夫でしょうか?

ご教授お願い申し上げます。

参考元サイト [やんばるエキスパート]
https://www.yanbaru-code.com/texts

2021-03-18 10:28 UTC, yamada1013 commented on app/controllers/texts_controller.rb
> +  PER_PAGE = 9
PER_PAGE = 18でよろしいでしょうか?

2021-03-18 11:23 UTC, ajk0421 commented
> > 各ページのPERが大きく変わらないのであれば ApplicationRecord >>でdefaultのPERを定義しておいて、
> > ApplicationRecord でdefaultのPERを定義しておいて、
> 
> ⇩ApplicationRecordでdefault定義したんですが反映されなかったです。
> ApplicationRecordでどのようにPERを定義すればよろしいでしょうか?
> 
> ```
> class ApplicationRecord < ActiveRecord::Base
>   paginates_per 3
>   self.abstract_class = true
> end
> ```
> 
> > > 変更がある場合、各modelでオーバーライドすると良いと思います！
> > > (意味が分からない場合は聞いてください！)
> 
> class ApplicationRecord < ActiveRecord::Baseで
> defaultで定義した後
> 例えばtext.rbでどのようにオーバーライドすればよろしいでしょうか？
> 
> ⇩class Text < ApplicationRecordでdefault定義したら反映されました。
> 
> ```
> class Text < ApplicationRecord
>   has_many :users
>   has_many :reads, dependent: :destroy
>   validates :genre, presence: true
>   validates :title, presence: true
>   validates :content, presence: true
>   
>   paginates_per 3
> 
>   def read_by?(user)
>     reads.find_by(user_id: user.id).present?
>   end
> end
> ```

えっと、

```
class ApplicationRecord < ActiveRecord::Base
  PER = 5
end
```

って定義しておけば、あとは、どのコントローラーでも `PER` を呼び出すだけです！

で

例えば、Textだけ変更したい！とかあれば


```
class Text < ApplicationRecord
  PER = 10
end
```
と書けば、Textだけ変更することが出来ます！


> 
> ターミナルにrails g kaminari:views bootstrap4をすると
> ページネーション部分が参考アプリのようなレイアウトになりましたが
> rails g kaminari:views bootstrap4は実行してもよろしいでしょうか?
> 
> 他の要らないファイルができるなどありますか?
> bootstrapをbootstrap4に指定しましたが
> 現在package.jsonでは "bootstrap": "^4.6.0",になっている場合でも
> 大丈夫でしょうか?
> 
> ご教授お願い申し上げます。
> 
> 参考元サイト [やんばるエキスパート]
> https://www.yanbaru-code.com/texts

ここは正直挙動を見てみなきゃなんですが、コンソールでエラーなど出ていなければとりあえずOKです！

2021-03-18 11:24 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +  PER_PAGE = 9
>PER_PAGE = 18でよろしいでしょうか?

ここはチームメンバー or ご自分の判断で構いません！

2021-03-19 06:29 UTC, yamada1013 commented on app/controllers/texts_controller.rb
> +  PER_PAGE = 9
承知しました。

2021-03-19 07:06 UTC, yamada1013 commented
>えっと、

```
  class ApplicationRecord < ActiveRecord::Base
   PER = 5
  end 
```
>って定義しておけば、あとは、どのコントローラーでも PER を呼び出すだけです！

>で

>例えば、Textだけ変更したい！とかあれば
```
class Text < ApplicationRecord
  PER = 10
end
```
>と書けば、Textだけ変更することが出来ます！

上記のように
`application.record.rb`
`text.rb`
にコードを書いたんですがエラーになりました。
このやり方ではできないのでしょうか?
ご教授お願い申し上げます。

昨日pullした
`デフォルト設定`
`PER_PAGE各々設定`
`kaminariのビューファイルを作成`
のようにすればできました。

`application.record.rb`
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  PER = 5
  
end
```
`text.rb`
```
class Text < ApplicationRecord
  has_many :users
  has_many :reads, dependent: :destroy
  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true

  PER = 10

  def read_by?(user)
    reads.find_by(user_id: user.id).present?
  end
end
```


`text_controller.rb`
```
class TextsController < ApplicationController
  #PER = 12
  def index
    @q = set_texts.ransack(params[:q])
    @texts = @q.result.page(params[:page]).per(PER)
  end

  def show
    @text = Text.find(params[:id])
  end

  private

  def set_texts
    if params[:q]
      @genre = params[:q]["genre"]
    else
      @genre = params[:genre]
    end

    search_genre = case @genre
      when "php"
        @title = "PHP"
        "Php"
      when "aws"
        @title = "AWS"
        "AWS"
      else
        @title = "Ruby/Rails"
        ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]
      end

    @texts = Text.where(genre: search_genre)
  end
end
```

>ここは正直挙動を見てみなきゃなんですが、コンソールでエラーなど出ていなければとりあえずOKです！

rails g kaminari:views bootstrap4は上手くできました。
ありがとうございます。

2021-03-19 11:59 UTC, ajk0421 requested changes

2021-03-19 11:59 UTC, ajk0421 commented on app/models/movie.rb
> +  paginates_per 9
```
paginates_per
```
こちらのメソッドでページ数を制御する場合は `PER` は不要ですね！
どちらかにしましょう！

2021-03-19 11:59 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +  PER_PAGE = 12
```
PER_PAGE = 12
```
コントローラーに基本定数は書かないですね！

2021-03-19 13:06 UTC, yamada1013 commented on app/models/movie.rb
> +  paginates_per 9
承知しました。
paginates_perを使うためPERを消します。

2021-03-19 13:06 UTC, yamada1013 commented on app/controllers/texts_controller.rb
> +  PER_PAGE = 12
承知しました。
定数をけします。

2021-03-20 07:34 UTC, ajk0421 requested changes

2021-03-20 07:34 UTC, ajk0421 commented on app/controllers/movies_controller.rb
> +    @movies = Movie.page(params[:page])
ここ元の実装を壊していませんか？

2021-03-21 06:35 UTC, yamada1013 commented on app/controllers/movies_controller.rb
> +    @movies = Movie.page(params[:page])
コメントありがとうございます

間違えてこちら消していました。
修正しましたのでお願いします。

2021-03-23 02:22 UTC, ajk0421 requested changes

2021-03-23 02:22 UTC, ajk0421 commented on app/controllers/movies_controller.rb
> +    @movies = @q.page(params[:page])
この `@q` はviewのどこかで使用してますか？？

2021-03-24 08:41 UTC, yamada1013 commented on app/controllers/movies_controller.rb
> +    @movies = @q.page(params[:page])
コメントありがとうございます。
使用していないです。
@movies = Movie.where(genre: search_genre).page(params[:page])に変更した方が良いでしょうか?

2021-03-24 08:44 UTC, ajk0421 commented on app/controllers/movies_controller.rb
> +    @movies = @q.page(params[:page])
使用しないインスタンス変数を定義するのは良くないので、変更しましょう！

2021-03-25 10:09 UTC, yamada1013 commented on app/controllers/movies_controller.rb
> +    @movies = @q.page(params[:page])
承知しました。

2021-03-25 10:17 UTC, ajk0421 approved these changes
動作確認が出来ていればマージしていただいて大丈夫です！！

2021-03-27 05:33 UTC, merged