LINE教材ページレイアウト
yanbaru-expert/team_project_42 pull request #67
Opened 2021-03-17 02:30 UTC by Shuto-Toyama

close #43 

## 実装内容

- LINE教材用CSSの設定
- LINE教材用背景色の設定
  - `stylesheet_helper.rb`を作成、LINEページに限り背景色を変更させる`bg_color`アクションを定義
  - `bg_color`アクションを`_header.html.erb`,` _footer.html.erb`に反映
  - `application.html.erb`の記述を調整

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-03-18 06:07 UTC, ajk0421 requested changes

2021-03-18 06:07 UTC, ajk0421 commented on app/helpers/stylesheet_helper.rb
> +  def bg_color
```
bg_color
```
`bg` ってなんでしょうか？メソッド名に略語を使うのはやめましょう！

2021-03-18 06:07 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +    <%= render 'layouts/header'%>
`<header></header>`  `<footer></footer>`
をパーシャル側に寄せた理由ってなんでしょうか？？

2021-03-18 20:26 UTC, Shuto-Toyama commented on app/helpers/stylesheet_helper.rb
> +  def bg_color
レビューありがとうございます。
「bg = background_color」としていました。
修正致します。

2021-03-18 20:35 UTC, Shuto-Toyama commented on app/views/layouts/application.html.erb
> +    <%= render 'layouts/header'%>
レビューありがとうございます！
`bg_color`メソッドを挿入する際に、
`<header></header> <footer></footer>`
それぞれパーシャルに入れた方が`app/views/layouts/application.html.erb`
の可読性が高まりスマートなのではないかと考え編集しました。
こちらは移動しないほうがよろしいでしょうか？？

2021-03-19 06:52 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +    <%= render 'layouts/header'%>
>それぞれパーシャルに入れた方がapp/views/layouts/application.html.erb
>の可読性が高まりスマートなのではないかと考え編集しました。

明確な理由があればそれで大丈夫です！

2021-03-19 07:34 UTC, Shuto-Toyama commented on app/views/layouts/application.html.erb
> +    <%= render 'layouts/header'%>
レビューありがとうございます！
承知致しました。

2021-03-19 08:02 UTC, ajk0421 approved these changes
OKです！
マージしてください！

2021-03-19 08:06 UTC, merged